# Generated by Django 6.0.3 on 2026-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                ("planted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
