# Generated by Django 6.0.3 on 2026-07-05 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_]{3,30}$",
                        "Username must be 3–30 characters: letters, numbers, or underscores.",
                    )
                ],
                verbose_name="nombre de usuario",
            ),
        ),
    ]
